#!/bin/sh
./search.sh SingleMu
./search.sh DY_10-50
./search.sh DY_50
./search.sh ttbar
./search.sh ZZ_inclusive
./search.sh WZ_inclusive
./search.sh WW_inclusive
./search.sh WpWp
./search.sh WmWm
./search.sh ttZ
./search.sh ttW
./search.sh ttWW
./search.sh WWW
./search.sh ZZZ
./search.sh WWZ
./search.sh WZZ
#./search.sh W_jets
#./search.sh QCD_mu15
